#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

git add .

# Run dotnet build and test before commit
echo "Building QuickBite API"
cd src/QuickBite.API
if ! dotnet build; then
  echo "Build failed. Commit aborted."
  exit 1
fi

# echo "checking format"
# if ! dotnet format --verify-no-changes; then
#   echo "Code format issues found. Please run 'dotnet format' to fix them. Commit aborted."
#   exit 1
# fi

echo "Running Tests"
cd ../../tests/QuickBite.API.Tests
if ! dotnet test; then
  echo "Tests failed. Commit aborted."
  exit 1
fi

# echo "checking format"
# if ! dotnet format --verify-no-changes; then
#   echo "Code format issues found. Please run 'dotnet format' to fix them. Commit aborted."
#   exit 1
# fi

echo "All checks passed. Proceeding with commit."