name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build-test-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/QuickBite.API/QuickBite.API.csproj

      - name: Build API
        run: dotnet build src/QuickBite.API/QuickBite.API.csproj --configuration Release --no-restore

      - name: Build Tests
        run: dotnet build tests/QuickBite.API.Tests/QuickBite.API.Tests.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test tests/QuickBite.API.Tests/QuickBite.API.Tests.csproj --no-build --verbosity normal

      - name: Check formatting (API project)
        run: dotnet format src/QuickBite.API/QuickBite.API.csproj --verify-no-changes

      - name: Check formatting (test project)
        run: dotnet format tests/QuickBite.API.Tests/QuickBite.API.Tests.csproj --verify-no-changes